=== fclemente10/XML-XSLT/SoccerDTD.dtd
<?xml version="1.0" encoding="utf-8" ?>

<!ELEMENT XMLSOCCER.COM (Player+)>
<!ELEMENT Player (Id, Name, Height?, Weight?, Nationality, Position, Team_Id, PlayerNumber?, LoanTo?, DateOfBirth?, DateOfSigning, Signing)>	

<!ELEMENT Id (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT Height (#PCDATA)>
<!ELEMENT Weight (#PCDATA)>
<!ELEMENT Nationality (#PCDATA)>
<!ELEMENT Position (#PCDATA)>
<!ELEMENT Team_Id (#PCDATA)>
<!ELEMENT PlayerNumber (#PCDATA)>
<!ELEMENT LoanTo (#PCDATA)>
<!ELEMENT DateOfBirth (#PCDATA)>
<!ELEMENT DateOfSigning (#PCDATA)>
<!ELEMENT Signing (#PCDATA)>

=== fclemente10/XML-XSLT/Aberdeen.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE XMLSOCCER.COM SYSTEM "./SoccerDTD.dtd">
<XMLSOCCER.COM>
<Player>
<Id>1375</Id>
<Name>Ryan McLaughlin </Name>
<Height>1.75</Height>
<Nationality>Northern Ireland</Nationality>
<Position>Defender</Position>
<Team_Id>820</Team_Id>
<PlayerNumber>2</PlayerNumber>
<LoanTo>45</LoanTo>
<DateOfBirth>1994-09-30T00:00:00+02:00</DateOfBirth>
<DateOfSigning>2019-01-23T00:00:00+01:00</DateOfSigning>
<Signing>Undisc.</Signing>
</Player>
<Player>
<Id>1571</Id>
<Name>Dominic Ball </Name>
<Nationality>England</Nationality>
<Position>Defender</Position>
<Team_Id>10</Team_Id>
<PlayerNumber>12</PlayerNumber>
<LoanTo>45</LoanTo>
<DateOfBirth>1995-08-02T00:00:00+02:00</DateOfBirth>
<DateOfSigning>2019-07-02T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>2045</Id>
<Name>Joe Lewis </Name>
<Height>1.96</Height>
<Weight>83.9</Weight>
<Nationality>England</Nationality>
<Position>Goalkeeper</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>1</PlayerNumber>
<LoanTo>4</LoanTo>
<DateOfBirth>1987-10-06T00:00:00+02:00</DateOfBirth>
<DateOfSigning>2016-06-15T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>2157</Id>
<Name>Aaron Lennox </Name>
<Nationality>Australia</Nationality>
<Position>Goalkeeper</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>30</PlayerNumber>
<LoanTo>562</LoanTo>
<DateOfBirth>1993-02-19T00:00:00+01:00</DateOfBirth>
<DateOfSigning>2016-01-26T00:00:00+01:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>2220</Id>
<Name>Craig Bryson </Name>
<Height>1.7</Height>
<Weight>58.96</Weight>
<Nationality>Scotland</Nationality>
<Position>Midfielder</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>7</PlayerNumber>
<LoanTo>44</LoanTo>
<DateOfBirth>1986-11-06T00:00:00+01:00</DateOfBirth>
<DateOfSigning>2019-07-01T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>2227</Id>
<Name>Max Lowe </Name>
<Nationality>England</Nationality>
<Position>Defender</Position>
<Team_Id>227</Team_Id>
<PlayerNumber>13</PlayerNumber>
<LoanTo>45</LoanTo>
<DateOfBirth>1997-05-11T00:00:00+02:00</DateOfBirth>
<DateOfSigning>2020-09-07T00:00:00+02:00</DateOfSigning>
<Signing>Undisc.</Signing>
</Player>
<Player>
<Id>2527</Id>
<Name>Gary Woods </Name>
<Height>1.8</Height>
<Weight>68.94</Weight>
<Nationality>England</Nationality>
<Position>Goalkeeper</Position>
<Team_Id>615</Team_Id>
<PlayerNumber>43</PlayerNumber>
<LoanTo>45</LoanTo>
<DateOfBirth>1990-10-01T00:00:00+02:00</DateOfBirth>
<DateOfSigning>2019-06-25T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>2537</Id>
<Name>Tommy Hoban </Name>
<Height>1.88</Height>
<Weight>84.35</Weight>
<Nationality>Ireland</Nationality>
<Position>Defender</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>3</PlayerNumber>
<LoanTo>45</LoanTo>
<DateOfBirth>1994-01-24T00:00:00+01:00</DateOfBirth>
<DateOfSigning>2020-07-31T00:00:00+02:00</DateOfSigning>
<Signing>Unknown</Signing>
</Player>
<Player>
<Id>2890</Id>
<Name>Simon Church </Name>
<Height>1.83</Height>
<Weight>83.45</Weight>
<Nationality>Wales</Nationality>
<Position>Forward</Position>
<Team_Id>226</Team_Id>
<PlayerNumber>23</PlayerNumber>
<LoanTo>45</LoanTo>
<DateOfBirth>1988-12-10T00:00:00+01:00</DateOfBirth>
<DateOfSigning>2017-10-01T00:00:00+02:00</DateOfSigning>
<Signing/>
</Player>
<Player>
<Id>2998</Id>
<Name>Dylan McGeouch </Name>
<Height>1.78</Height>
<Nationality>Scotland</Nationality>
<Position>Midfielder</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>15</PlayerNumber>
<LoanTo>53</LoanTo>
<DateOfBirth>1993-01-15T00:00:00+01:00</DateOfBirth>
<DateOfSigning>2020-01-07T00:00:00+01:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>3008</Id>
<Name>Andrew Considine </Name>
<Height>1.83</Height>
<Weight>73.47</Weight>
<Nationality>Scotland</Nationality>
<Position>Defender</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>4</PlayerNumber>
<DateOfBirth>1987-04-01T00:00:00+02:00</DateOfBirth>
<DateOfSigning>2004-04-24T00:00:00+02:00</DateOfSigning>
<Signing>Youth</Signing>
</Player>
<Player>
<Id>3010</Id>
<Name>Shaleum Logan </Name>
<Height>1.73</Height>
<Weight>78.91</Weight>
<Nationality>England</Nationality>
<Position>Defender</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>2</PlayerNumber>
<DateOfBirth>1988-01-29T00:00:00+01:00</DateOfBirth>
<DateOfSigning>2014-05-27T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>3013</Id>
<Name>Niall McGinn </Name>
<Height>1.78</Height>
<Weight>73.47</Weight>
<Nationality>Northern Ireland</Nationality>
<Position>Midfielder</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>10</PlayerNumber>
<DateOfBirth>1987-07-20T00:00:00+02:00</DateOfBirth>
<DateOfSigning>2012-07-04T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>3014</Id>
<Name>Jonny Hayes </Name>
<Height>1.7</Height>
<Weight>69.84</Weight>
<Nationality>Ireland</Nationality>
<Position>Midfielder</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>17</PlayerNumber>
<DateOfBirth>1987-07-09T00:00:00+02:00</DateOfBirth>
<DateOfSigning>2020-07-01T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>3020</Id>
<Name>Craig Storie </Name>
<Nationality>Scotland</Nationality>
<Position>Midfielder</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>23</PlayerNumber>
<LoanTo>674</LoanTo>
<DateOfBirth>1996-01-13T00:00:00+01:00</DateOfBirth>
<DateOfSigning>2013-01-01T00:00:00+01:00</DateOfSigning>
<Signing>Youth</Signing>
</Player>
<Player>
<Id>3021</Id>
<Name>Calvin Zola </Name>
<Height>1.91</Height>
<Weight>86.17</Weight>
<Nationality>DR Congo</Nationality>
<Position>Forward</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>10</PlayerNumber>
<DateOfBirth>1984-12-31T00:00:00+01:00</DateOfBirth>
<DateOfSigning>2014-06-20T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>3104</Id>
<Name>Marley Watkins </Name>
<Height>1.85</Height>
<Weight>64.4</Weight>
<Nationality>Wales</Nationality>
<Position>Forward</Position>
<Team_Id>26</Team_Id>
<PlayerNumber>50</PlayerNumber>
<LoanTo>45</LoanTo>
<DateOfBirth>1990-10-17T00:00:00+02:00</DateOfBirth>
<DateOfSigning>2018-06-01T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>3105</Id>
<Name>Greg Tansey </Name>
<Height>1.85</Height>
<Weight>78</Weight>
<Nationality>England</Nationality>
<Position>Midfielder</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>16</PlayerNumber>
<DateOfBirth>1988-11-21T00:00:00+01:00</DateOfBirth>
<DateOfSigning>2017-06-09T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>3259</Id>
<Name>Kenny McLean </Name>
<Height>1.83</Height>
<Weight>70.75</Weight>
<Nationality>Scotland</Nationality>
<Position>Midfielder</Position>
<Team_Id>13</Team_Id>
<PlayerNumber>23</PlayerNumber>
<LoanTo>45</LoanTo>
<DateOfBirth>1992-01-08T00:00:00+01:00</DateOfBirth>
<DateOfSigning>2018-01-22T00:00:00+01:00</DateOfSigning>
<Signing>Undisc.</Signing>
</Player>
<Player>
<Id>9554</Id>
<Name>Adam Collin </Name>
<Height>1.91</Height>
<Weight>78</Weight>
<Nationality>England</Nationality>
<Position>Goalkeeper</Position>
<Team_Id>816</Team_Id>
<PlayerNumber>1</PlayerNumber>
<LoanTo>45</LoanTo>
<DateOfBirth>1984-12-09T00:00:00+01:00</DateOfBirth>
<DateOfSigning>2018-07-04T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>9561</Id>
<Name>Kari Arnason </Name>
<Height>1.91</Height>
<Weight>87.08</Weight>
<Nationality>Iceland</Nationality>
<Position>Defender</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>14</PlayerNumber>
<DateOfBirth>1982-10-13T00:00:00+02:00</DateOfBirth>
<DateOfSigning>2017-07-14T00:00:00+02:00</DateOfSigning>
<Signing>Undisc.</Signing>
</Player>
<Player>
<Id>9842</Id>
<Name>Wes Burns </Name>
<Height>1.7</Height>
<Nationality>Wales</Nationality>
<Position>Forward</Position>
<Team_Id>830</Team_Id>
<PlayerNumber>7</PlayerNumber>
<LoanTo>45</LoanTo>
<DateOfBirth>1994-11-23T00:00:00+01:00</DateOfBirth>
<DateOfSigning>2017-01-19T00:00:00+01:00</DateOfSigning>
<Signing>Undisc.</Signing>
</Player>
<Player>
<Id>9939</Id>
<Name>Ash Taylor </Name>
<Height>1.83</Height>
<Weight>76.19</Weight>
<Nationality>Wales</Nationality>
<Position>Defender</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>14</PlayerNumber>
<DateOfBirth>1990-09-02T00:00:00+02:00</DateOfBirth>
<DateOfSigning>2019-06-04T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>10386</Id>
<Name>Michael Devlin </Name>
<Height>1.88</Height>
<Nationality>Scotland</Nationality>
<Position>Defender</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>6</PlayerNumber>
<DateOfBirth>1993-10-03T00:00:00+02:00</DateOfBirth>
<DateOfSigning>2018-01-26T00:00:00+01:00</DateOfSigning>
<Signing>Undisc.</Signing>
</Player>
<Player>
<Id>10426</Id>
<Name>Gavin Rae </Name>
<Height>1.75</Height>
<Weight>64.4</Weight>
<Nationality>Scotland</Nationality>
<Position>Midfielder</Position>
<Team_Id>45</Team_Id>
<DateOfBirth>1977-11-28T00:00:00+01:00</DateOfBirth>
<DateOfSigning>2013-07-01T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>10780</Id>
<Name>Stephen Gleeson </Name>
<Height>1.75</Height>
<Weight>79.37</Weight>
<Nationality>Ireland</Nationality>
<Position>Midfielder</Position>
<Team_Id>45</Team_Id>
<PlayerNumber>8</PlayerNumber>
<DateOfBirth>1988-08-03T00:00:00+02:00</DateOfBirth>
<DateOfSigning>2018-06-19T00:00:00+02:00</DateOfSigning>
<Signing>Free</Signing>
</Player>
<Player>
<Id>10948</Id>
<Name>Scott Wright </Name>
<Nationality>Scotland</Nationality>
<Position>Forward</Position>
<Team_Id>49</Team_Id>
<PlayerNumber>25</PlayerNumber>
<LoanTo>45</LoanTo>
